const EXAM_DATA = [
  {
    id: '1-1',
    title: '1. Sınav: Görüntü İşleme',
    summary: '<b>Arayüz ve Araçlar:</b> Photoshop arayüzü, seçim araçları, kesme ve rötuş araçlarını kapsar. <br><br><b>Renk Modları:</b> Dijital için RGB, baskı için CMYK kullanılır. Katmanlar (Layers) çalışma düzenini sağlar; Actions ise toplu işlemleri otomatiğe bağlar.',
    questions: [
      { q: "Seçimi tersine çevirmek için hangi kısayol kullanılır?", a: "Shift + Ctrl + I" },
      { q: "Baskı alınacak bir görselde hangi renk modu seçilmelidir?", a: "CMYK" },
      { q: "Katmanı silmeden gizlemek için ne yapılır?", a: "Yanındaki göz sembolüne tıklanır." },
      { q: "Birden fazla fotoğrafa aynı efekti otomatik uygulamak için ne kullanılır?", a: "Actions (Eylemler)" },
      { q: "Bir görüntüyü perspektif bozulmalarını düzelterek kırpan araç nedir?", a: "Perspective Crop Tool" },
      { q: "Katmanların bir klasör altında toplanmasına ne denir?", a: "Katman Grupları" },
      { q: "Web sayfası tasarlarken dilimleme neden yapılır?", a: "Dosyaların hızlı yüklenmesi ve link verilmesi için." },
      { q: "\"Tsume\" ayarı nedir?", a: "Karakterler arası boşlukların sıkıştırılması." },
      { q: "Bir metni resme dönüştürme işlemine ne denir?", a: "Rasterize" },
      { q: "Görüntü boyutunu değiştirmek için hangi menü kullanılır?", a: "Image > Image Size" }
    ],
    flashcards: [
      { front: ".psd", back: "Görüntü işleme programının ham dosya formatı." },
      { front: "RGB", back: "Dijital görüntüler için ışık bazlı renk modu." },
      { front: "CMYK", back: "Baskı alınacak görüntüler için boya bazlı renk modu." },
      { front: "Katman (Layer)", back: "Çalışmaların kontrolünü sağlayan nesneler." },
      { front: "Magic Wand", back: "Toleransa göre benzer renkleri seçen araç." },
      { front: "Crop Tool", back: "Gereksiz alanları kaldırma aracı." },
      { front: "Actions", back: "İşlemleri kaydedip tekrar kullanma paneli." },
      { front: "Slice Tool", back: "Web arayüzünde bölüp link verme aracı." },
      { front: "Ctrl + D", back: "Seçimi iptal etme (Deselect) kısayolu." },
      { front: "Ctrl + A", back: "Tüm alanı seçme (Select All) kısayolu." },
      { front: "Shift + Ctrl + I", back: "Seçimi tersine çevirme (Inverse)." },
      { front: "Opacity", back: "Katmanın saydamlık değeri." },
      { front: "Patch Tool", back: "Dokuyu kullanarak kusurları onarma aracı." },
      { front: "Brightness", back: "Parlaklık ayarı." },
      { front: "Contrast", back: "Açık ve koyu renk arasındaki fark." },
      { front: "Artboards", back: "Farklı ekran boyutları için tasarım alanları." },
      { front: "Character Paneli", back: "Yazı tipi ve boyutu ayarları." },
      { front: "Filter Gallery", back: "Görüntüye çeşitli efektler uygulama alanı." },
      { front: "Quick Export PNG", back: "Belgeyi hızla PNG olarak dışa aktarma." },
      { front: "Ruler Tool", back: "Uzaklık ve açı ölçme aracı." }
    ]
  },
  {
    id: '1-2',
    title: '2. Sınav: Efekt Yazılımı Temelleri',
    summary: '<b>After Effects Temelleri:</b> Project, Composition ve Timeline ana panellerdir. <br><br><b>Transform:</b> Position (P), Scale (S), Rotation (R) ve Opacity (T) temel kısayollardır. Render işlemleri için Render Queue veya Media Encoder kullanılır.',
    questions: [
      { q: "Katmanlı bir dosyayı tüm katmanlarıyla aktarmak için hangi seçenek kullanılır?", a: "Import As > Composition" },
      { q: "Nesnenin hareket merkezini değiştiren araç hangisidir?", a: "Pan Behind (Anchor Point) Tool" },
      { q: "Projeyi tam ekran ön izlemek için ne seçilmelidir?", a: "Preview > Full Screen" },
      { q: "Zaman çizelgesinde nesneye hareket vermek için ne kullanılır?", a: "Keyframe (Anahtar Kare)" },
      { q: "Bir kompozisyonu başka bir kompozisyon içine almaya ne denir?", a: "Pre-composition" },
      { q: ".avi formatında çıktı almak için hangi uygulama kullanılır?", a: "Media Encoder" },
      { q: "Panelleri varsayılan hale getirmek için hangi seçenek seçilir?", a: "Reset \"Default\" to Saved Layout" },
      { q: "Bir resmin belirli bir bölgesini kopyalayıp başka yere aktaran araç nedir?", a: "Clone Stamp Tool" },
      { q: "Bir videoyu maskelemek için Pen aracı ne zaman kullanılır?", a: "Katman seçiliyken." },
      { q: "Transform ayarlarından \"T\" harfi neyi açar?", a: "Opacity (Şeffaflık)" }
    ],
    flashcards: [
      { front: "Project Paneli", back: "Dosyaların (video, resim) dâhil edildiği alan." },
      { front: "Composition", back: "Projenin ana çalışma sahnesi." },
      { front: "Timeline", back: "Zaman çizelgesi ve katman yönetimi." },
      { front: "Footage", back: "Tek bir katman olarak aktarılan materyal." },
      { front: "V tuşu", back: "Seçim aracı (Selection Tool) kısayolu." },
      { front: "H tuşu", back: "El aracı (Hand Tool) kısayolu." },
      { front: "Position", back: "Nesnenin sahmedeki konumu (P kısayolu)." },
      { front: "Scale", back: "Nesnenin büyüklüğü (S kısayolu)." },
      { front: "Rotation", back: "Nesnenin dönme açısı (R kısayolu)." },
      { front: "Opacity", back: "Nesnenin görünürlüğü (T kısayolu)." },
      { front: "Anchor Point", back: "Nesnenin merkez (çıpa) noktası." },
      { front: "Render Queue", back: "Çıktı kuyruğu paneli." },
      { front: "FPS", back: "Saniyedeki kare sayısı." },
      { front: "Ctrl + 0", back: "Proje panelini gizle/göster." },
      { front: "Star Tool", back: "Yıldız şekli çizme aracı." },
      { front: "Media Encoder", back: "Farklı formatlarda çıktı alma programı." },
      { front: "Pen Tool", back: "Serbest şekil çizme ve maskeleme aracı." },
      { front: "Ctrl + D", back: "Katmanı çoğaltma (Duplicate) kısayolu." },
      { front: "Info Paneli", back: "Renkli ve konum bilgilerini gösteren panel." },
      { front: "Preview", back: "Animasyonun ön izlemesini yapma." }
    ]
  },
  {
    id: '2-1',
    title: '3. Sınav: Hareketli Görüntüler',
    summary: '<b>Gelişmiş Teknikler:</b> Graph Editor ile hız ayarı, Parenting ile hiyerarşi ve Null Object ile kontrol sağlanır. <br><br><b>Değiştiriciler:</b> Şekil katmanlarında Repeater ve Trim Paths kullanılır. Puppet Tool ile durağan resimler canlandırılır.',
    questions: [
      { q: "Hangi araç nesnelere bağlantı noktası ekleyerek onları kukla gibi hareket ettirir?", a: "Puppet Pin Tool" },
      { q: "Bir şekli 6 adet kopya yapmak için hangi düzenleyici kullanılır?", a: "Repeater" },
      { q: "Yazının bir çember etrafında dönmesi için hangi özellik anime edilir?", a: "First Margin" },
      { q: "Anahtar kareyi silmek için hangi tuşa basılır?", a: "Delete" },
      { q: "Katman süresini kısaltmak için ne yapılır?", a: "Süre çubuğunun ucundan tutulup sürüklenir." },
      { q: "Metnin karakter özelliklerini değiştiren panel hangisidir?", a: "Character Paneli" },
      { q: "Sallanma efekti veren script (komut) nedir?", a: "Wiggle" },
      { q: "Bir katmanın özelliklerini diğerine aktarmak için ne kullanılır?", a: "Parenting (Ebeveynlik)" },
      { q: "Çizginin zamanla belirmesini sağlayan komut nedir?", a: "Trim Paths" },
      { q: "Katmanı sahnede ortalamak için hangi panel kullanılır?", a: "Align" }
    ],
    flashcards: [
      { front: "Keyframe", back: "Zaman içindeki değişim noktası." },
      { front: "Graph Editor", back: "Hareket hızını grafiksel düzenleme alanı." },
      { front: "Parenting", back: "Bir katmanı diğerine bağlama işlemi." },
      { front: "Null Object", back: "Görünmeyen katman kontrol nesnesi." },
      { front: "Repeater", back: "Şekli belirli sayıda çoğaltan değiştirici." },
      { front: "Wiggle Paths", back: "Kenarlara rastgele sallanma veren özellik." },
      { front: "Trim Paths", back: "Çizgiyi zamanla çizme veya yok etme." },
      { front: "Puppet Pin", back: "Nesneye hareket noktası ekleme." },
      { front: "Easy Ease", back: "Hareketi yumuşatma (F9 tuşu)." },
      { front: "CTI", back: "Zaman göstergesi (Current Time Indicator)." },
      { front: "Source Text", back: "Metin içeriğini anahtar karelerle değiştirme." },
      { front: "Stroke", back: "Kenarlık stili." },
      { front: "Pre-compose", back: "Katmanları tek grup haline getirme." },
      { front: "Twist", back: "Kendi ekseninde bükme efekti." },
      { front: "First Margin", back: "Yol üzerindeki metnin başlangıç konumu." },
      { front: "Mask Expansion", back: "Maske alanını büyütme/küçültme." },
      { front: "Motion Blur", back: "Gerçekçi hareket bulanıklığı." },
      { front: "Space", back: "Ön izlemeyi başlatma/durdurma." },
      { front: "Alt + Click", back: "Kronometreye basıp Expression ekleme." },
      { front: "Dashes", back: "Çizgiyi kesikli hale getirme özelliği." }
    ]
  },
  {
    id: '2-2',
    title: '4. Sınav: Maskeleme ve VFX',
    summary: '<b>Görsel Efektler:</b> Chroma Key (Yeşil Perde) ve Rotoskop teknikleri ile arka plan temizleme işlenir. <br><br><b>3D Dünyası:</b> 3D Layer, Kamera ve Işık kullanımıyla derinlik sağlanır. Scriptler (Wiggle, Time) ile hareket otomatiği kurulur.',
    questions: [
      { q: "Yeşil perde çekiminde özne üzerinde hangi renk bulunmamalıdır?", a: "Yeşil" },
      { q: "Hareketli videodaki kişiyi ayırmak için en uygun araç nedir?", a: "Roto Brush" },
      { q: "Işık nesnesine gölge oluşturması için hangi özellik açılmalıdır?", a: "Cast Shadows" },
      { q: "Maske özelliklerine erişmek için hangi kısayol kullanılır?", a: "M tuşu" },
      { q: "Videonun derinliğini analiz edip yazı sabitleyen efekt nedir?", a: "3D Camera Tracker" },
      { q: "Maske kenarlarındaki keskinliği azaltan özellik hangisidir?", a: "Feather" },
      { q: "Görsel efekt programında kaç temel kamera tipi vardır?", a: "2 (One-node ve Two-node)" },
      { q: "wiggle(10,30) komutundaki 10 sayısı neyi ifade eder?", a: "Saniyedeki sallanma sayısı (frekans)." },
      { q: "Efekt kontrol panelini açıp kapatan kısayol nedir?", a: "F3" },
      { q: "Şekil katmanına eklendiğinde deformasyon (bükülme) yapan nedir?", a: "Twist" }
    ],
    flashcards: [
      { front: "Chroma Key", back: "Belirli bir rengi saydamlaştırma." },
      { front: "Keylight", back: "Yeşil perde temizleme efektidir." },
      { front: "Alpha Matte", back: "Üst katman şekline göre maskeleme." },
      { front: "Luma Matte", back: "Parlaklık değerine göre maskeleme." },
      { front: "Roto Brush", back: "Hareketli nesneleri fırçayla boyayarak ayırma." },
      { front: "Expression", back: "Kod yazarak animasyon yapma." },
      { front: "3D Layer", back: "Z ekseni derinliği kazandırma (Küp simgesi)." },
      { front: "Point Light", back: "Her yöne ışık yayan kaynak." },
      { front: "Cast Shadows", back: "Nesne gölgesi oluşturma ayarı." },
      { front: "3D Tracker", back: "Hareketi analiz edip nesne sabitleme." },
      { front: "Mask Feather", back: "Maske kenarlarını yumuşatma." },
      { front: "Adjustment Layer", back: "Altındaki tüm katmanlara efekt uygulayan katman." },
      { front: "Plugin", back: "Ek özellik ve efekt paketleri." },
      { front: "Refine Edge", back: "Saç gibi ince detayların maske iyileştirmesi." },
      { front: "Track Matte", back: "Katman tabanlı maskeleme paneli." },
      { front: "Mesh Warp", back: "Görseli ızgarayla deforme etme." },
      { front: "Curves", back: "Renk ve ışık dengesini grafiksel ayarlama." },
      { front: "Two-Node Cam", back: "Konumu ve bakış noktası olan kamera." },
      { front: "Inverted", back: "Maske alanını tersine çevirme." },
      { front: "Fractal Noise", back: "Rastgele doku ve gürültü efekti." }
    ]
  }
];

window.EXAM_DATA = EXAM_DATA;
